In [2]:
import pandas as pd
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[22,23,24]
df['City']=['Chennai','Pune','Hyderabad']

**step10: replace**

In [2]:
df

     Names  Age       City
0   Ramesh   22    Chennai
1   Suresh   23       Pune
2  Sathish   24  Hyderabad

In [3]:
df.replace('Ramesh','Prashanti') #inplace do not happen then it will not overwrite

       Names  Age       City
0  Prashanti   22    Chennai
1     Suresh   23       Pune
2    Sathish   24  Hyderabad

In [4]:
df

     Names  Age       City
0   Ramesh   22    Chennai
1   Suresh   23       Pune
2  Sathish   24  Hyderabad

In [9]:
import pandas as pd
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[22,23,24]
df['City']=['Hyderabad','Pune','Hyderabad']
df["marks"]=[12,14,16]

In [10]:
df

     Names  Age       City  marks
0   Ramesh   22  Hyderabad     12
1   Suresh   23       Pune     14
2  Sathish   24  Hyderabad     16

In [11]:
df.replace(12,45)

     Names  Age       City  marks
0   Ramesh   22  Hyderabad     45
1   Suresh   23       Pune     14
2  Sathish   24  Hyderabad     16

In [13]:
df["marks"].replace(22,24,inplace=True)

In [14]:
df

     Names  Age       City  marks
0   Ramesh   22  Hyderabad     12
1   Suresh   23       Pune     14
2  Sathish   24  Hyderabad     16

In [ ]:
#i want to change city name to chennai
# for those candidate who have age=24

**step11-np.where**

In [3]:
import numpy as np

np.where(condition,True,False)
age==24
chennai
Nochange

In [ ]:
#I need to apply conditionn on age column
# we need to select a column
con=df["Age"]==24

In [21]:
con=df["Age"]==24
true="Chennai"
false=df["City"]

In [24]:
df['City']=np.where(con,true,false)

In [25]:
df

     Names  Age       City  marks
0   Ramesh   22  Hyderabad     12
1   Suresh   23       Pune     14
2  Sathish   24    Chennai     16

In [27]:
df

     Names  Age       City  marks
0   Ramesh   22  Hyderabad     12
1   Suresh   23       Pune     14
2  Sathish   24    Chennai     16

**loc-iloc**

In [ ]:
df.loc[rows,columns]
 rows are like index numbers similar list slicing
l[start:stop:step]
columns are names any column name we can provide
df.iloc[rows,columns]
rows and columns are index number similar to list slice
l[start:stop:step]

In [5]:
rows=[1,2]
cols=['Age','City']
df.loc[rows,cols]

   Age       City
1   23       Pune
2   24  Hyderabad

In [37]:
cols=['Age','City']
df.loc[1:3,cols]

   Age     City
1   23     Pune
2   24  Chennai

In [41]:
df.loc[2]=['Anish',34,'bhopal',88]

In [42]:
df

    Names  Age       City  marks
0  Ramesh   22  Hyderabad     12
1  Suresh   23       Pune     14
2   Anish   34     bhopal     88

In [36]:
rows=[0,1]
cols=[2,3]
df.iloc[rows,cols]

        City  marks
0  Hyderabad     12
1       Pune     14

**step-13:how to save the dataframe**

In [53]:
#directory:where is the file available
#name:what is the name if file
#exteension: what is the type of file

###############################################
        #python location
#name:what is the name of file
#extension:what is the type of file

#dataframe variable=df
#name:student
#extensioon:.csv and .xlsv

df.to_csv('student.csv')

In [54]:
pd.read_csv('student.csv')

   Unnamed: 0   Names  Age       City  marks
0           0  Ramesh   22  Hyderabad     12
1           1  Suresh   23       Pune     14
2           2   Anish   34     bhopal     88

In [56]:
df.read_xlsv('student.xlsv')

AttributeError: 'DataFrame' object has no attribute 'read_xlsv'

In [57]:
df.to_excel('student.xlsx')

In [58]:
pd.read_excel('student.xlsx')

   Unnamed: 0   Names  Age       City  marks
0           0  Ramesh   22  Hyderabad     12
1           1  Suresh   23       Pune     14
2           2   Anish   34     bhopal     88

In [ ]:
#take a new notebook
#in your datafiles
#visadataset
#bankdataset pls load
#visadataset and all type of dataset

In [3]:
import pandas as pd

In [4]:
pd.read_csv(r"C:\Users\Prachi Choudhary\Downloads\Visadataset.csv")

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified