step1:import packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**srep2: create a dataframe using list**

In [2]:
Names=["Ramesh","Suresh","Satish"]
#pd.Dataframe(data,index,columns)
pd.DataFrame(Names)

        0
0  Ramesh
1  Suresh
2  Satish

**step3:name the column**

In [4]:
Names=["Ramesh","Suresh","Satish"]
#pd.DataFrame(data,index,columns)
pd.DataFrame(Names,columns=['Names'])

    Names
0  Ramesh
1  Suresh
2  Satish

**step4:chnage the index**

In [5]:
Names=["Ramesh","Suresh","Satish"]
pd.DataFrame(Names,index=["A","B","C"],columns=['Names'])

    Names
A  Ramesh
B  Suresh
C  Satish

**step5:two columns**

In [14]:
Names=["Ramesh","Suresh","Satish"]
Age=[20,22,24]
data=zip(Names,Age)
cols=["Names","Age"]
pd.DataFrame(data,columns=cols)

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

**step6:add data to empty dataframe**

In [15]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [2]:
df=pd.DataFrame()
df["Names"]=["Ramesh","Suresh","Satish"]
df["Age"]=[20,22,24]
df

NameError: name 'pd' is not defined

**Error**
- key error=columns not equal
- dimension error=column length is mismatched

In [17]:
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

In [19]:
#already data frame is available then add a column to existing dataframe
df["City"]=["Chennai","Pune","Mumbai"]
df

    Names  Age     City
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

**Methods**

**step8:rename the column**

In [20]:
# i want the rename from capital city to small city
#df.rename(mapper,index,columns,axis,inplace)
d={'City':'city'}
df.rename(columns=d)

    Names  Age     city
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [24]:
d={'City':'city'}
df.rename(d)
df.rename(axis=0)#index
df.rename(axis=1)#column
df.rename(index=d)#index
df.rename(columns=d)#columns

TypeError: Cannot specify both 'mapper' and any of 'index' or 'columns'

In [27]:
d={'City':'city'}
df.rename(columns=d)

    Names  Age     city
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [28]:
d={'City':'city'}
df.rename(d)

    Names  Age     City
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [29]:
d={'City':'city'}
df.rename(index=d)

    Names  Age     City
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [31]:
d={'City':'city'}
df.rename(d,axis=0)

    Names  Age     City
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [32]:
d={'City':'city'}
df.rename(d,axis=1)

    Names  Age     city
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [33]:
df.columns=["names","age","city"]

In [34]:
df

    names  age     city
0  Ramesh   20  Chennai
1  Suresh   22     Pune
2  Satish   24   Mumbai

In [35]:
df.index=["s","q","p"]

In [36]:
df

    names  age     city
s  Ramesh   20  Chennai
q  Suresh   22     Pune
p  Satish   24   Mumbai

**#step9:drop the columns**

In [2]:
#I want to drop"city columns"
df.drop('City')

NameError: name 'df' is not defined

In [1]:
df.drop('age',axis=1)

NameError: name 'df' is not defined

In [50]:
df

    names  age     city
s  Ramesh   20  Chennai
q  Suresh   22     Pune
p  Satish   24   Mumbai

In [4]:
d={'City':'city'}
df.rename(d,axis=1)
df.drop('c')

NameError: name 'df' is not defined

In [ ]:
Names=["Ramesh","Sures",""]
city=
age=[]
data=zip()
df=pd.datafrme